name: '⚙️ api'

on:
  workflow_dispatch:
  push:
    branches: ['main']

concurrency:
  group: '${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}'

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: sa-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
  
      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 21
  
      - name: "Install Serverless Framework"
        run: npm install -g serverless@3
  
      - name: "Install Dependencies"
        run: npm install
  
      - name: "Build"
        run: make build
  
      - name: Serverless deploy 
        run: |
          make deploy
  
